import type { BlogPost, Product } from "./types";

export const products: Product[] = [
  {
    id: "el-colono-molido",
    slug: "el-colono-premium-molido-250g",
    brand: "El Colono",
    name: "Premium molido tradicional",
    format: "Molido",
    weightG: 250,
    descriptionShort: "Listo para preparar, equilibrado y práctico para el consumo cotidiano.",
    description: "Una alternativa de entrada para mejorar el café de todos los días sin necesitar molino. Funciona bien en casa, oficina o para compartir con visitas.",
    priceCents: null,
    stock: null,
    availability: "available",
    variety: null,
    origin: "Oxapampa",
    roast: "Medio",
    process: null,
    tastingNotes: [],
    methods: ["Cafetera", "Prensa", "Filtro"],
    moments: ["Todos los días"],
    featured: true,
  },
  {
    id: "el-colono-especial",
    slug: "el-colono-premium-presentacion-especial-250g",
    brand: "El Colono",
    name: "Premium presentación especial",
    format: "Presentación especial",
    weightG: 250,
    descriptionShort: "El café molido de la línea Premium en una presentación pensada para regalar.",
    description: "Un detalle útil y bien presentado para ocasiones personales, familiares o profesionales. No requiere molino y mantiene la practicidad de la línea Premium.",
    priceCents: null,
    stock: null,
    availability: "available",
    variety: null,
    origin: "Oxapampa",
    roast: "Medio",
    process: null,
    tastingNotes: [],
    methods: ["Cafetera", "Prensa", "Filtro"],
    moments: ["Regalo"],
    featured: true,
  },
  {
    id: "el-colono-grano",
    slug: "el-colono-premium-en-grano-250g",
    brand: "El Colono",
    name: "Premium en grano",
    format: "En grano",
    weightG: 250,
    descriptionShort: "Para moler al momento y ajustar la molienda al método de preparación.",
    description: "Permite conservar mejor el café hasta el momento de prepararlo y elegir una molienda adecuada para cada método.",
    priceCents: null,
    stock: null,
    availability: "available",
    variety: null,
    origin: "Oxapampa",
    roast: "Medio",
    process: null,
    tastingNotes: [],
    methods: ["Prensa", "Filtro", "Espresso"],
    moments: ["Moler al momento"],
    featured: true,
  },
  {
    id: "kienti-typica",
    slug: "kienti-typica",
    brand: "Kiénti",
    name: "Typica",
    format: "Por confirmar",
    weightG: null,
    descriptionShort: "Café de variedad Typica para explorar una propuesta distinta por variedad.",
    description: "La ficha queda preparada para mostrar origen, proceso, tueste, notas y métodos apenas se confirmen los datos del producto.",
    priceCents: null,
    stock: null,
    availability: "available",
    variety: "Typica",
    origin: null,
    roast: null,
    process: null,
    tastingNotes: [],
    methods: [],
    moments: ["Explorar variedades"],
    featured: false,
  },
  {
    id: "kienti-catimor",
    slug: "kienti-catimor",
    brand: "Kiénti",
    name: "Catimor",
    format: "Por confirmar",
    weightG: null,
    descriptionShort: "Café de variedad Catimor para comparar perfiles y conocer nuevas opciones.",
    description: "La ficha queda preparada para mostrar origen, proceso, tueste, notas y métodos apenas se confirmen los datos del producto.",
    priceCents: null,
    stock: null,
    availability: "available",
    variety: "Catimor",
    origin: null,
    roast: null,
    process: null,
    tastingNotes: [],
    methods: [],
    moments: ["Explorar variedades"],
    featured: false,
  },
];

export const posts: BlogPost[] = [
  {
    id: "molido-o-grano",
    slug: "cafe-molido-o-en-grano",
    title: "Café molido o en grano: cómo elegir según tu rutina",
    excerpt: "Una guía directa para escoger la presentación que realmente encaja con tu forma de preparar café.",
    category: "Guías",
    publishedAt: "2026-07-20",
    readingMinutes: 4,
    featured: true,
    body: [
      "Elegir entre café molido y café en grano depende menos de una regla universal y más de cómo preparas tu café cada día.",
      "El café molido es práctico: abres el paquete, mides la cantidad y preparas. Es una buena opción si buscas consistencia y no quieres incorporar un molino a tu rutina.",
      "El café en grano permite moler al momento y ajustar la molienda al método. Requiere un paso adicional, pero ofrece mayor control sobre la preparación.",
      "Si todavía no tienes claro qué elegir, empieza por identificar tu método, el tiempo que dedicas a preparar el café y si prefieres practicidad o control.",
    ],
  },
  {
    id: "conservar-cafe",
    slug: "como-conservar-el-cafe",
    title: "Cómo conservar el café después de abrirlo",
    excerpt: "Cuatro decisiones simples que ayudan a proteger el café del aire, la humedad y el calor.",
    category: "Cuidado",
    publishedAt: "2026-07-18",
    readingMinutes: 3,
    featured: false,
    body: [
      "Después de abrir el empaque, conviene mantener el café bien cerrado y lejos de fuentes de calor o humedad.",
      "Usa el cierre del propio empaque o un recipiente limpio y hermético. Guárdalo en un espacio fresco y evita dejarlo cerca de la cocina o bajo luz directa.",
      "Comprar una cantidad adecuada a tu consumo también ayuda: es preferible terminar el paquete en un periodo razonable que almacenar más café del necesario.",
    ],
  },
  {
    id: "preparar-mejor",
    slug: "mejorar-cafe-en-casa",
    title: "Tres ajustes para preparar un mejor café en casa",
    excerpt: "Cantidad, agua y limpieza: tres variables concretas para mejorar sin complicar tu rutina.",
    category: "Preparación",
    publishedAt: "2026-07-16",
    readingMinutes: 4,
    featured: false,
    body: [
      "Una mejor preparación no siempre exige comprar más equipos. A menudo empieza por repetir una proporción, cuidar el agua y mantener limpio el método.",
      "Mide la misma cantidad de café y agua durante varios días. Esa referencia te permite ajustar con intención, en lugar de cambiar varias cosas a la vez.",
      "Evita agua con sabores u olores fuertes y limpia los utensilios después de cada uso. Los residuos acumulados pueden afectar el resultado de la siguiente preparación.",
    ],
  },
];
