// Catálogo de países para el onboarding de Qaway Hub.
// rucDigitos: dígitos del identificador fiscal (RUC) cuando aplica.
// minDigitos: mínimo de dígitos para un número local válido (sin contar el prefijo).
export const PAISES = [
  { nombre: "Perú", codigo: "PE", dial: "+51", rucDigitos: 11, minDigitos: 9 },
  { nombre: "Argentina", codigo: "AR", dial: "+54", rucDigitos: 11, minDigitos: 8 },
  { nombre: "Australia", codigo: "AU", dial: "+61", rucDigitos: null, minDigitos: 9 },
  { nombre: "Bélgica", codigo: "BE", dial: "+32", rucDigitos: null, minDigitos: 8 },
  { nombre: "Bolivia", codigo: "BO", dial: "+591", rucDigitos: 7, minDigitos: 7 },
  { nombre: "Brasil", codigo: "BR", dial: "+55", rucDigitos: 14, minDigitos: 10 },
  { nombre: "Canadá", codigo: "CA", dial: "+1", rucDigitos: null, minDigitos: 10 },
  { nombre: "Chile", codigo: "CL", dial: "+56", rucDigitos: 8, minDigitos: 8 },
  { nombre: "China", codigo: "CN", dial: "+86", rucDigitos: 18, minDigitos: 6 },
  { nombre: "Colombia", codigo: "CO", dial: "+57", rucDigitos: 9, minDigitos: 10 },
  { nombre: "Costa Rica", codigo: "CR", dial: "+506", rucDigitos: 10, minDigitos: 8 },
  { nombre: "Cuba", codigo: "CU", dial: "+53", rucDigitos: null, minDigitos: 7 },
  { nombre: "Ecuador", codigo: "EC", dial: "+593", rucDigitos: 13, minDigitos: 8 },
  { nombre: "El Salvador", codigo: "SV", dial: "+503", rucDigitos: 14, minDigitos: 8 },
  { nombre: "España", codigo: "ES", dial: "+34", rucDigitos: 9, minDigitos: 9 },
  { nombre: "Estados Unidos", codigo: "US", dial: "+1", rucDigitos: null, minDigitos: 10 },
  { nombre: "Francia", codigo: "FR", dial: "+33", rucDigitos: null, minDigitos: 9 },
  { nombre: "Guatemala", codigo: "GT", dial: "+502", rucDigitos: null, minDigitos: 8 },
  { nombre: "Honduras", codigo: "HN", dial: "+504", rucDigitos: null, minDigitos: 8 },
  { nombre: "India", codigo: "IN", dial: "+91", rucDigitos: null, minDigitos: 10 },
  { nombre: "Italia", codigo: "IT", dial: "+39", rucDigitos: null, minDigitos: 9 },
  { nombre: "Japón", codigo: "JP", dial: "+81", rucDigitos: null, minDigitos: 10 },
  { nombre: "México", codigo: "MX", dial: "+52", rucDigitos: 13, minDigitos: 10 },
  { nombre: "Nicaragua", codigo: "NI", dial: "+505", rucDigitos: null, minDigitos: 8 },
  { nombre: "Panamá", codigo: "PA", dial: "+507", rucDigitos: null, minDigitos: 8 },
  { nombre: "Paraguay", codigo: "PY", dial: "+595", rucDigitos: null, minDigitos: 9 },
  { nombre: "Países Bajos", codigo: "NL", dial: "+31", rucDigitos: null, minDigitos: 9 },
  { nombre: "Portugal", codigo: "PT", dial: "+351", rucDigitos: null, minDigitos: 9 },
  { nombre: "Puerto Rico", codigo: "PR", dial: "+1 787", rucDigitos: null, minDigitos: 10 },
  { nombre: "Reino Unido", codigo: "GB", dial: "+44", rucDigitos: null, minDigitos: 10 },
  { nombre: "República Dominicana", codigo: "DO", dial: "+1 809", rucDigitos: null, minDigitos: 10 },
  { nombre: "Suiza", codigo: "CH", dial: "+41", rucDigitos: null, minDigitos: 9 },
  { nombre: "Uruguay", codigo: "UY", dial: "+598", rucDigitos: null, minDigitos: 8 },
  { nombre: "Venezuela", codigo: "VE", dial: "+58", rucDigitos: null, minDigitos: 7 },
];