// Canónico v4. Barrel curado. Re-exports explícitos para preservar tree-shaking.
// Prohibido `export * from 'lucide-react'`.
export {
  Search,
  Plus,
  X,
  Bell,
  Calendar,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Settings,
  Settings2,
  User,
  Users,
  Layers,
  LayoutDashboard,
  FolderKanban,
  Kanban,
  FileText,
  BarChart3,
  MessageSquare,
  Zap,
  Target,
  Briefcase,
  Clock,
  Check,
  CheckCircle2,
  AlertCircle,
  SlidersHorizontal,
  Share2,
  ExternalLink,
  TrendingUp,
  Sparkles,
  PenTool,
  BookOpen,
  Building2,
  LogOut,
  Workflow,
  Globe,
  LayoutGrid,
  FileEdit,
  Video,
  GraduationCap,
  RefreshCw,
  ShieldCheck,
  Menu,
  Home,
  Bot,
  CalendarDays,
  Package,
  Clapperboard,
  PenLine,
  MessageSquareText,
  CreditCard,
  KanbanSquare,
  ArrowRight,
  ArrowUpRight,
  Send,
  Paperclip,
  Phone,
  Filter,
  ArrowUpDown,
  Flame,
  Star,
  FileImage,
  Instagram,
  PenSquare,
  Route,
  FlaskConical,
  Wrench,
  HelpCircle,
  Tag,
  Receipt,
  Shield,
  UserPlus,
} from 'lucide-react'

export const HUB_ICON_NAMES = {
  dashboard: 'LayoutDashboard|BarChart3',
  leads: 'Users',
  pipeline: 'Layers|Kanban',
  search: 'Search',
  plus: 'Plus',
  bell: 'Bell',
  calendar: 'Calendar',
} as const
